# Generated by Django 3.1.1 on 2020-09-24 19:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='WA', max_length=50)),
                ('nickname', models.CharField(max_length=20, null=True)),
                ('date', models.CharField(max_length=20, null=True)),
                ('score', models.CharField(max_length=10, null=True)),
                ('text', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreDB2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('visitors_reviews', models.IntegerField()),
                ('blog_reviews', models.IntegerField()),
                ('call', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('operation', models.CharField(max_length=30)),
                ('naver_link', models.TextField()),
                ('score', models.CharField(max_length=10)),
                ('category', models.CharField(default='식당', max_length=10)),
                ('addcode', models.CharField(default='서울', max_length=10)),
                ('predict', models.CharField(default='[0, 0, 0, 0, 0, 0, 0]', max_length=30)),
                ('liked_users', models.ManyToManyField(related_name='liked_posts2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('visitors_reviews', models.IntegerField()),
                ('blog_reviews', models.IntegerField()),
                ('call', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('operation', models.CharField(max_length=30)),
                ('naver_link', models.TextField()),
                ('score', models.CharField(max_length=10)),
                ('category', models.CharField(default='식당', max_length=10)),
                ('addcode', models.CharField(default='서울', max_length=10)),
                ('predict', models.CharField(default='[0, 0, 0, 0, 0, 0, 0]', max_length=30)),
                ('liked_users', models.ManyToManyField(related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
