# Generated by Django 3.1.1 on 2020-09-23 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('visitors_reviews', models.IntegerField()),
                ('blog_reviews', models.IntegerField()),
                ('call', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('operation', models.CharField(max_length=30)),
                ('naver_link', models.TextField()),
                ('score', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.IntegerField()),
                ('score', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reivew', to='NotHereApp.storedb')),
            ],
        ),
    ]
