# Generated by Django 3.1.1 on 2020-09-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotHereApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedb',
            name='addcode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='storedb',
            name='category',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
