# Generated by Django 3.1.1 on 2020-09-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotHereApp', '0002_auto_20200923_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedb',
            name='addcode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='storedb',
            name='category',
            field=models.CharField(max_length=10),
        ),
    ]
