# Generated by Django 3.1.1 on 2020-09-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotHereApp', '0003_auto_20200923_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdb',
            name='date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reviewdb',
            name='nickname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
