# Generated by Django 3.1.1 on 2020-09-24 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NotHereApp', '0004_auto_20200924_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedb',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
