# Generated by Django 3.1.1 on 2020-09-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotHereApp', '0005_storedb_liked_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewdb',
            name='review_id',
        ),
        migrations.RemoveField(
            model_name='reviewdb',
            name='store_id',
        ),
        migrations.AddField(
            model_name='reviewdb',
            name='store_name',
            field=models.CharField(default='WA', max_length=50),
        ),
        migrations.AddField(
            model_name='storedb',
            name='predict',
            field=models.CharField(default='[0, 0, 0, 0, 0, 0, 0]', max_length=30),
        ),
        migrations.AlterField(
            model_name='reviewdb',
            name='score',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reviewdb',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
